"""Sample Arachne Script

This script provides an example on how a graph is built in Arachne from two Arkouda arrays and then
analyzed using Arachne functions. The graphs are randomly generated by using the ak.randint function
with the range of the vertex names being picked from 0..<n and the number of edges m. No special
distribution is used to generated the graph e.g. RMAT. 

The values of n and m are accepted from command line input. It requires Arkouda and Arachne to both
be pip installed in the environment. 

Assumes Arkouda server is running. It will shutdown the Arkouda server upon completion.

Sample usage: python3 arachne_simple_tests.py n51 5555 -n 5000 -m 20000

"""
import argparse
import arkouda as ak
import arachne as ar

def create_parser():
    """Creates the command line parser for this script"""
    script_parser = argparse.ArgumentParser(
        description="Simple script showcasing all the functionality of Arachne on a random graph of\
                     size specified by the user."
    )
    script_parser.add_argument("hostname", help="Hostname of arkouda server")
    script_parser.add_argument("port", type=int, default=5555, help="Port of arkouda server")
    script_parser.add_argument("n", type=int, default=1000, help="Number of vertices for graph")
    script_parser.add_argument("m", type=int, default=2000, help="Number of edges for graph")

    return script_parser

if __name__ == "__main__":
    # Command line parser and extraction.
    parser = create_parser()
    args = parser.parse_args()
    
    # Connect to the Arkouda server.
    ak.verbose = False
    ak.connect(args.hostname, args.port)

    # Build graph from two source and destination arrays.
    src = ak.randint(0, args.n, args.m)
    dst = ak.randint(0, args.n, args.m)
    print(f"Building graph with arrays {src.name} and {dst.name} ...")
    graph = ar.Graph()
    graph.add_edges_from(src,dst)
    print(f"Built graph with {graph.n_vertices} vertices and {graph.n_edges} edges.")

    ak.shutdown()
